19 grobes app layout
eerieFoods/PizzaBrei pull request #31
Opened 2022-12-09 10:46 UTC by Rexphel

Closes #19

2022-12-09 10:53 UTC, JayReturns requested changes

2022-12-09 10:53 UTC, JayReturns commented on pb-app/.idea/compiler.xml
> +    <annotationProcessing>
bitte .idea ordner nicht mit pushen

2022-12-09 10:53 UTC, JayReturns commented on pb-app/app/src/main/java/com/github/eeriefoods/pizzabrei/data/datasource/backend/entity/ApplicationEntity.kt
> +package com.github.eeriefoods.pizzabrei.data.datasource.backend.entity
wird die Datei benötigt?

2022-12-09 10:53 UTC, JayReturns commented on pb-app/app/src/main/java/com/github/eeriefoods/pizzabrei/data/datasource/backend/entity/ReviewEntity.kt
> +package com.github.eeriefoods.pizzabrei.data.datasource.backend.entity
same here?

2022-12-09 10:53 UTC, JayReturns commented on pb-app/app/src/main/res/values-night/colors.xml
> +</resources>
Wieso gibt's das und die Colors.kt?

2022-12-10 22:34 UTC, Rexphel commented on pb-app/app/src/main/res/values-night/colors.xml
> +</resources>
überbleibsel aus dem pre Compose. Wird aber von einigen res verwendet.

2022-12-10 22:35 UTC, Rexphel commented on pb-app/app/src/main/java/com/github/eeriefoods/pizzabrei/data/datasource/backend/entity/ReviewEntity.kt
> +package com.github.eeriefoods.pizzabrei.data.datasource.backend.entity
same up

2022-12-12 18:43 UTC, AlexSchmitz222 commented on pb-app/app/src/main/java/com/github/eeriefoods/pizzabrei/data/repository/ApplicationAPIImpl.kt
> +//TODO ADD BACKEND API CALLS//
tztztz...

2022-12-12 18:44 UTC, JayReturns approved these changes

2022-12-12 18:45 UTC, AlexSchmitz222 reviewed
boah ja keine Ahnung Mann. sieht lustig aus aber ka ob's richtig ist so.
lieber nochmal Jay gucken lassen <3

2022-12-12 18:45 UTC, merged